### man qsub !
### join stdout and stderr
#$ -j y
### change to currend work dir
#$ -cwd
### send mail to
#$ -M martin.voegele@biophys.mpg.de
### send no email
#$ -m n
### request the parallel environment with 20 physical cores == 1 nodes
#$ -pe impi_hydra 24 
### request 24 hours wallclock
#$ -l h_rt=24:00:00
### job name
#$ -N OKCp07m01


## MODULES ##

# load the impi module (-> mandatory)
module load impi/4.1.3
module load gromacs/4.6.7-plumed2.1


## SIMULATION ##

# Directory
OLDDIR=$( pwd )
cd simulation

# MD simulation
mpiexec -np 4  mdrun_mpi -v -deffnm martini_md -cpi martini_md.cpt -cpt 5 -rdd 2


cd ..

exit 0
